# EXPERIMENT 2 - NUMERICAL PYTHON (NUMPY)

In [1]:
import numpy as np

## NORMALIZATION PROBLEM

In [15]:
# Create a random 5x5 ndarray and store it in variable X

# Use np.random.rand to generate random numbers between 0 and 1
X = np.random.rand(5, 5)

print("Original 5x5 ndarray (X):\n", X)

Original 5x5 ndarray (X):
 [[0.38591136 0.73538574 0.18796042 0.23889108 0.40926287]
 [0.69114384 0.17248074 0.13336449 0.27479756 0.32006006]
 [0.34371002 0.83591374 0.46676374 0.78669938 0.67223315]
 [0.42908182 0.13888708 0.07297899 0.71815425 0.32950075]
 [0.21730547 0.71113367 0.58099473 0.50582811 0.31936879]]


In [16]:
# Normalize the matrix

# np.mean(X) gives the mean of all elements
# np.std(X) gives the standard deviation of all elements
X_normalized = (X - X.mean()) / X.std() # Normalization formula: Z = (X - mean) / std

print("\nNormalized 5x5 ndarray:\n", X_normalized)


Normalized 5x5 ndarray:
 [[-0.18214937  1.36287053 -1.0572869  -0.8321234  -0.07891277]
 [ 1.16727791 -1.12572232 -1.29865455 -0.6733815  -0.47327679]
 [-0.36872075  1.80730302  0.17529752  1.58972722  1.08367411]
 [ 0.00870643 -1.27423927 -1.56561773  1.28669045 -0.43153966]
 [-0.92755297  1.2556526   0.68031067  0.34800041 -0.47633289]]


In [17]:
# Save the result to a file for later use

# The .npy format is NumPy’s standard for saving arrays
np.save("X_normalized.npy", X_normalized)

## DIVISIBLE BY 3 PROBLEM

In [18]:
# Create a 10x10 ndarray with squares of the first 100 positive integers

# np.arange(1, 101) generates numbers from 1 to 100
# **2 squares each number
# .reshape(10,10) turns the flat list into a 10x10 matrix
A = np.arange(1, 101).reshape(10, 10) ** 2

print("\n10x10 ndarray of squares of first 100 integers (A):\n", A)


10x10 ndarray of squares of first 100 integers (A):
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [19]:
# Find all elements divisible by 3

# A % 3 == 0 creates a boolean mask of True/False values
# A[A % 3 == 0] extracts only the values divisible by 3
div_by_3 = A[A % 3 == 0]

print("\nElements divisible by 3:\n", div_by_3)


Elements divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


In [20]:
# Save the result
np.save("div_by_3.npy", div_by_3)